feat: React: Table Component(#41046)
AryanSinghal/javascript-client pull request #16
Opened 2020-03-20 12:51 UTC by AryanSinghal

2020-03-31 13:37 UTC, Rahul-Successive requested changes

2020-03-31 13:37 UTC, Rahul-Successive commented on src/pages/Trainee/components/Table.jsx
> +                <TableRow key={row.name}>
how do you know there will be a key called **name** in the data of the rows?

2020-03-31 13:47 UTC, AryanSinghal commented on src/pages/Trainee/components/Table.jsx
> +                <TableRow key={row.name}>
it is given in the dummy object on redmine.

2020-04-08 11:59 UTC, Rahul-Successive approved these changes

2020-04-08 11:59 UTC, merged