feat: Spinner, Axios login and routes authorize (#41251)
AryanSinghal/javascript-client pull request #23
Opened 2020-06-02 08:49 UTC by AryanSinghal

2020-06-03 13:27 UTC, Rahul-Successive requested changes

2020-06-03 13:27 UTC, Rahul-Successive commented on package.json
> +    "dotenv": "^8.2.0",
why are you using dotenv?

2020-06-03 13:27 UTC, Rahul-Successive commented on src/Layout/components/Navbar/Navbar.jsx
> +                (!localStorage.getItem('token'))
What is this?

2020-06-03 13:27 UTC, Rahul-Successive commented on src/pages/Login/Login.jsx
> +        {
Again why it is there?

2020-06-03 13:27 UTC, Rahul-Successive commented on src/routes/PrivateRoute.jsx
> +    {
Move this code outside of JSX Scope

2020-06-03 13:47 UTC, AryanSinghal commented on package.json
> +    "dotenv": "^8.2.0",
Because we are said to do so

2020-06-04 06:00 UTC, AryanSinghal commented on src/Layout/components/Navbar/Navbar.jsx
> +                (!localStorage.getItem('token'))
I have made the changes

2020-06-04 06:01 UTC, AryanSinghal commented on src/pages/Login/Login.jsx
> +        {
I have made the changes

2020-06-04 06:01 UTC, AryanSinghal commented on src/routes/PrivateRoute.jsx
> +    {
ok sir

2020-06-04 08:43 UTC, Rahul-Successive approved these changes

2020-06-04 08:43 UTC, merged